@startuml 

autonumber
actor "Courier" as C

activate C
C -> ":System" : begins the process of knowing the amount of energy required to make a delivery run
activate ":System"
":System" --> C : asks for the necessary data(delivery run)
deactivate ":System"

C -> ":System" : inserts the solicited data
activate ":System"
":System" --> C : validates the data, presents it and asks the Courier for its confirmation
deactivate ":System"

C -> ":System" : confirms
activate ":System"
":System" --> C : shows the information requested
deactivate ":System"

deactivate C

@enduml