@startuml 

autonumber
actor "Administrator" as ADM

activate ADM
ADM -> ":System" : begins the process of removing a drone
activate ":System"
":System" --> ADM : shows a list of drones and asks which one is to be removed
deactivate ":System"

ADM -> ":System" : picks one drone
activate ":System"
":System" --> ADM : validates the information, presents it and asks the administrator for its confirmation
deactivate ":System"

ADM -> ":System" : confirms
activate ":System"
":System" --> ADM : removes the drone from the list
deactivate ":System"

deactivate ADM

@enduml