--USER_ROLE
INSERT INTO USER_ROLE (ID_USER_ROLE, DESCRIPTION) VALUES(1, 'Administrator');
INSERT INTO USER_ROLE (ID_USER_ROLE, DESCRIPTION) VALUES(2, 'Courier');
INSERT INTO USER_ROLE (ID_USER_ROLE, DESCRIPTION) VALUES(3, 'Client');
INSERT INTO USER_ROLE (ID_USER_ROLE, DESCRIPTION) VALUES(4, 'Disabled');

--USER ENTRY
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('admin1@isep.ipp.pt', 'admin1',1);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('admin2@isep.ipp.pt', 'admin2',1);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('admin3@isep.ipp.pt', 'admin3',1);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client1@isep.ipp.pt', 'client1',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client2@isep.ipp.pt', 'client2',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client3@isep.ipp.pt', 'client3',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client4@isep.ipp.pt', 'client4',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client5@isep.ipp.pt', 'client5',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client6@isep.ipp.pt', 'client6',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client7@isep.ipp.pt', 'client7',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client8@isep.ipp.pt', 'client8',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client9@isep.ipp.pt', 'client9',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client10@isep.ipp.pt', 'client10',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client11@isep.ipp.pt', 'client11',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('client12@isep.ipp.pt', 'client12',3);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier1@isep.ipp.pt', 'courier1',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier2@isep.ipp.pt', 'courier2',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier3@isep.ipp.pt', 'courier3',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier4@isep.ipp.pt', 'courier4',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier5@isep.ipp.pt', 'courier5',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier6@isep.ipp.pt', 'courier6',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier7@isep.ipp.pt', 'courier7',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier8@isep.ipp.pt', 'courier8',2);
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('courier9@isep.ipp.pt', 'courier9',2);

--ADDRESS
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(1,  41.154578, -8.631177,'Rua Goncalo Sampaio','4450-136',81);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(2,  41.151527, -8.629040,'Rua da Piedade','4450-126',57);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(3,  41.152325, -8.626058,'Rua Julio Dinis','4450-116',72);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(4,  41.148171, -8.624156,'Rua Dom Manuel II','4450-133',77);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(5,  41.150151, -8.631217,'Rua da Pena','4450-100',69);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(6,  41.152665, -8.620806,'Rua da Torrinha','4450-057',87);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(7,  41.150722, -8.617192,'Rua de Cedofeita','4450-001',98);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(8,  41.152396, -8.615685,'Rua da Faculdade de Direito','4450-876',112);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(9,  41.151709, -8.613817,'Rua dos Martires da Liberdade','4450-256',117);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(10,  41.156299, -8.619319,'Rua da Boavista','4450-333',85);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(11,  41.156851, -8.616390,'Rua da Manutencao','4450-222',98);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(12,  41.155336, -8.613358,'Rua da Lapa','4450-136',114);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(13,  41.152532, -8.618049,'Rua dos Bragas','4450-137',102);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(14,  41.153772, -8.613262,'Pra�a da Republica','4450-137',111);
INSERT INTO ADDRESS (ID_ADDRESS, LATITUDE, LONGITUDE, ADDRESS, ZIP_CODE, ELEVATION) VALUES(15,  41.154563, -8.615206,'Rua Alvares Cabral','4450-137',117);


--ROAD
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(1, 1,2,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(2, 1,3,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(3, 5,1,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(4, 6,1,0.75);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(5, 6,10,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(6, 2,4,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(7, 3,4,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(8, 4,5,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(9, 4,6,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(10, 10,11,0.9);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(11, 11,10,0.9);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(12, 10,12,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(13, 12,10,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(14, 7,6,0.8);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(15, 10,13,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(16, 13,7,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(17, 7,8,0.85);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(18, 8,7,0.85);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(19, 7,9,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(20, 9,7,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(21, 8,9,0.9);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(22, 9,8,0.9);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(23, 8,15,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(24, 15,12,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(25, 12,14,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(26, 14,9,0.7);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(27, 11,12,0.9);
INSERT INTO ROAD (ID_ROAD, FK_ADDRESS_ID_START, FK_ADDRESS_ID_END, KINETIC_COEFICIENT) VALUES(28, 12,11,0.9);

--PERSON
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(260486306, 'admin1','admin1@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(212038467, 'admin2','admin2@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(132451352, 'admin3','admin3@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(223153497, 'client1','client1@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(240410727, 'client2','client2@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(216466039, 'client3','client3@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(221414079, 'client4','client4@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(262779086, 'client5','client5@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(208019513, 'client6','client6@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(254240337, 'client7','client7@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(293057872, 'client8','client8@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(251682962, 'client9','client9@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(273248196, 'client10','client10@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(194362136, 'client11','client11@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(208952980, 'client12','client12@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(113444253, 'courier1','courier1@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(148395616, 'courier2','courier2@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(112809681, 'courier3','courier3@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(169385432, 'courier4','courier4@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(184658989, 'courier5','courier5@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(221231244, 'courier6','courier6@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(124125464, 'courier7','courier7@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(132514123, 'courier8','courier8@isep.ipp.pt');
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(144535723, 'courier9','courier9@isep.ipp.pt');

--PHARMACY
INSERT INTO PHARMACY (ID_PHARMACY, NAME, MAXIMUM_PAYLOAD, MINIMUM_PAYLOAD, FK_ADDRESS_ID, FK_ADMINISTRATOR_EMAIL,ISACTIVE) VALUES(1, 'Pharmacy1',9,3,3,'admin1@isep.ipp.pt','true');
INSERT INTO PHARMACY (ID_PHARMACY, NAME, MAXIMUM_PAYLOAD, MINIMUM_PAYLOAD, FK_ADDRESS_ID, FK_ADMINISTRATOR_EMAIL,ISACTIVE) VALUES(2, 'Pharmacy2',10,4,13,'admin2@isep.ipp.pt','true');
INSERT INTO PHARMACY (ID_PHARMACY, NAME, MAXIMUM_PAYLOAD, MINIMUM_PAYLOAD, FK_ADDRESS_ID, FK_ADMINISTRATOR_EMAIL,ISACTIVE) VALUES(3, 'Pharmacy3',11,5,9,'admin3@isep.ipp.pt','true');

--COURIER TYPE STATUS
INSERT INTO COURIER_TYPE_STATUS (ID_COURIER_TYPE_STATUS, DESCRIPTION) VALUES(1, 'Free');
INSERT INTO COURIER_TYPE_STATUS (ID_COURIER_TYPE_STATUS, DESCRIPTION) VALUES(2, 'Busy');

--COURIER
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(113444253, 1,70.5,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(148395616, 1,80,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(112809681, 1,85,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(169385432, 2,90,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(184658989, 2,65,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(221231244, 2,95,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(124125464, 3,100,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(132514123, 3,60,'true');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(144535723, 3,50,'true');

--COURIER STATUS
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(113444253, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),1);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(148395616, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),2);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(112809681, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),3);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(169385432, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),4);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(184658989, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),5);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(221231244, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),6);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(124125464, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),7);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(132514123, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),8);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(144535723, 1,to_date('2020-01-01','yyyy-mm-dd HH24:mi:ss'),9);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(113444253, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),10);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(148395616, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),11);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(112809681, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),12);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(169385432, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),13);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(184658989, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),14);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(221231244, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),15);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(124125464, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),16);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(132514123, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),17);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(144535723, 2,to_date('2020-01-02','yyyy-mm-dd HH24:mi:ss'),18);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(113444253, 1,to_date('2020-01-03','yyyy-mm-dd HH24:mi:ss'),19);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(112809681, 1,to_date('2020-01-03','yyyy-mm-dd HH24:mi:ss'),20);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(169385432, 1,to_date('2020-01-03','yyyy-mm-dd HH24:mi:ss'),21);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(221231244, 1,to_date('2020-01-03','yyyy-mm-dd HH24:mi:ss'),22);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(124125464, 1,to_date('2020-01-03','yyyy-mm-dd HH24:mi:ss'),23);
INSERT INTO COURIER_STATUS (FK_PERSON_NIF, FK_COURIER_TYPE_STATUS_ID,Date_Entry,ID_COURIER_STATUS) VALUES(144535723, 1,to_date('2020-01-03','yyyy-mm-dd HH24:mi:ss'),24);

--PARK
INSERT INTO PARK (FK_PHARMACY_ID, SCOOTER_CHARGERS_NUMBER, DRONE_CHARGERS_NUMBER, Scooter_Charger_Capacity, DRONE_Charger_Capacity) VALUES(1, 10, 6, 100, 60);
INSERT INTO PARK (FK_PHARMACY_ID, SCOOTER_CHARGERS_NUMBER, DRONE_CHARGERS_NUMBER, Scooter_Charger_Capacity, DRONE_Charger_Capacity) VALUES(2, 13, 7, 100, 60);
INSERT INTO PARK (FK_PHARMACY_ID, SCOOTER_CHARGERS_NUMBER, DRONE_CHARGERS_NUMBER, Scooter_Charger_Capacity, DRONE_Charger_Capacity) VALUES(3, 16, 10, 100, 60);

--BATTERY
INSERT INTO BATTERY (ID_BATTERY, CAPACITY) VALUES(1, 45);
INSERT INTO BATTERY (ID_BATTERY, CAPACITY) VALUES(2, 60);

--VEHICLE_TYPE_STATUS
INSERT INTO VEHICLE_TYPE_STATUS (ID_VEHICLE_TYPE_STATUS, DESCRIPTION) VALUES(1, 'Charged');
INSERT INTO VEHICLE_TYPE_STATUS (ID_VEHICLE_TYPE_STATUS, DESCRIPTION) VALUES(2, 'Charging');
INSERT INTO VEHICLE_TYPE_STATUS (ID_VEHICLE_TYPE_STATUS, DESCRIPTION) VALUES(3, 'Undocked');
INSERT INTO VEHICLE_TYPE_STATUS (ID_VEHICLE_TYPE_STATUS, DESCRIPTION) VALUES(4, 'Docked');
INSERT INTO VEHICLE_TYPE_STATUS (ID_VEHICLE_TYPE_STATUS, DESCRIPTION) VALUES(5, 'Transiting');

--VEHICLE_TYPE
INSERT INTO VEHICLE_TYPE (ID_VEHICLE_TYPE, DESCRIPTION) VALUES(1, 'Scooter');
INSERT INTO VEHICLE_TYPE (ID_VEHICLE_TYPE, DESCRIPTION) VALUES(2, 'Drone');



--VEHICLE
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(1, 1,1,1,140,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(2, 1,2,2,100,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(3, 1,1,3,140,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(4, 2,2,4,100,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(5, 2,1,5,140,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(6, 2,2,6,100,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(7, 3,1,7,140,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(8, 3,2,8,100,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(9, 3,1,9,140,1,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(10, 1,1,1,20,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(11, 1,2,2,30,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(12, 1,1,3,20,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(13, 2,2,4,30,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(14, 2,1,5,20,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(15, 2,2,6,30,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(16, 3,1,7,20,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(17, 3,2,8,30,2,'true');
INSERT INTO VEHICLE (ID_VEHICLE, FK_PHARMACY_ID, FK_BATTERY_ID, QRCODE, WEIGHT, FK_VEHICLE_TYPE_ID, ISAVAILABLE) VALUES(18, 3,1,9,20,2,'true');


--VEHICLE STATUS
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(1, 1,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(2, 2,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(3, 3,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(4, 4,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(5, 5,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(6, 6,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(7, 7,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(8, 8,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(9, 9,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(10, 10,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(11, 11,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(12, 12,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(13, 13,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(14, 14,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(15, 15,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(16, 16,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(17, 17,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(18, 18,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(19, 1,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(20, 2,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(21, 3,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(22, 4,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(23, 5,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(24, 6,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(25, 7,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(26, 8,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(27, 9,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(28, 10,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(29, 11,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(30, 12,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(31, 13,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(32, 14,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(33, 15,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(34, 16,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(35, 17,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(36, 18,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),80);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(37, 1,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(38, 3,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(39, 5,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(40, 7,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(41, 9,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(42, 11,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(43, 13,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(44, 15,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);
INSERT INTO VEHICLE_STATUS (ID_VEHICLE_STATUS, FK_VEHICLE_ID, FK_VEHICLE_TYPE_STATUS_ID, DATE_ENTRY, ACTUALCHARGE) VALUES(45, 17,1,to_date('2020-01-03','YYYY-MM-DD HH24:MI:SS'),100);

--PRODUCT
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, PRICE, WEIGHT) VALUES(1, 'Vacina 1',10,30);
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, PRICE, WEIGHT) VALUES(2, 'Vacina 2',12,40);
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, PRICE, WEIGHT) VALUES(3, 'Vacina 3',14,50);
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, PRICE, WEIGHT) VALUES(4, 'Vacina 4',16,60);
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, PRICE, WEIGHT) VALUES(5, 'Vacina 5',18,70);
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, PRICE, WEIGHT) VALUES(6, 'Vacina 6',20,80);

--PHARMACY_PRODUCT
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(1, 1,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(2, 1,2,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(4, 1,4,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(5, 1,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(6, 1,6,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(7, 2,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(8, 2,2,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(9, 2,3,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(10, 2,4,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(11, 2,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(13, 3,1,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(14, 3,2,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(15, 3,3,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(16, 3,4,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(17, 3,5,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);
INSERT INTO PHARMACY_PRODUCT (ID_TRANSACTION, FK_PHARMACY_ID, FK_PRODUCT_ID, DATE_ENTRY, QUANTITY) VALUES(18, 3,6,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'),5);


--ORDER TYPE STATUS
INSERT INTO ORDER_TYPE_STATUS (ID_ORDER_TYPE_STATUS,DESCRIPTION) VALUES (1,'Pending');
INSERT INTO ORDER_TYPE_STATUS (ID_ORDER_TYPE_STATUS,DESCRIPTION) VALUES (2,'Ready to Deliver');
INSERT INTO ORDER_TYPE_STATUS (ID_ORDER_TYPE_STATUS,DESCRIPTION) VALUES (3,'In Transit');
INSERT INTO ORDER_TYPE_STATUS (ID_ORDER_TYPE_STATUS,DESCRIPTION) VALUES (4,'Canceled');
INSERT INTO ORDER_TYPE_STATUS (ID_ORDER_TYPE_STATUS,DESCRIPTION) VALUES (5,'Delivered');
INSERT INTO ORDER_TYPE_STATUS (ID_ORDER_TYPE_STATUS,DESCRIPTION) VALUES (6,'Not Delivered');

--CLIENT
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(223153497, 1);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(240410727, 2);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(216466039, 4);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(221414079, 5);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(262779086, 6);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(208019513, 7);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(254240337, 8);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(293057872, 10);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(251682962, 11);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(273248196, 12);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(194362136, 14);
INSERT INTO CLIENT (FK_PERSON_NIF, Fk_Residential_Address_Id) VALUES(208952980, 15);


--CREDIT CARD
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(223153497, 111,835627731957,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(240410727, 111,648047437165,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(216466039, 111,625322271164,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(221414079, 111,288964953761,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(262779086, 111,495473870069,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(208019513, 111,399078336652,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(254240337, 111,632715569103,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(293057872, 111,295626393615,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(251682962, 111,137916586739,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(273248196, 111,307878986586,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(194362136, 111,333362773618,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));
INSERT INTO CREDIT_CARD (FK_PERSON_NIF, CCV, NUMERO, VALID_THRU) VALUES(208952980, 111,391032308202,to_date('2020-01-01','YYYY-MM-DD HH24:MI:SS'));



--INSERT INTO COURIER (NUMERO, FK_PERSON_NIF, CCV, VALID_THRU) VALUES(223153497, 123,to_date(sysdate, 'yyyy-mm-dd'),11112222333);
--INSERT INTO COURIER (NUMERO, FK_PERSON_NIF, CCV, VALID_THRU) VALUES(240410727, 456,to_date(sysdate, 'yyyy-mm-dd'),1111221233330);

/**
--testes--
--admin test--
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('adminteste@isep.ipp.pt', 'adminteste',1);
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(222777898, 'adminteste','adminteste@isep.ipp.pt');

--pharmacy test--
INSERT INTO PHARMACY (ID_PHARMACY, NAME, MAXIMUM_PAYLOAD_COURIER, MINIMUM_LOAD_COURIER, FK_ADDRESS_ID, FK_ADMINISTRATOR_EMAIL) VALUES(3, 'PharmacyTest1',9,3,3,'adminteste@isep.ipp.pt');
INSERT INTO PHARMACY (ID_PHARMACY, NAME, MAXIMUM_PAYLOAD_COURIER, MINIMUM_LOAD_COURIER, FK_ADDRESS_ID, FK_ADMINISTRATOR_EMAIL) VALUES(4, 'PharmacyTest2',9,3,4,'adminteste@isep.ipp.pt');

--courier
INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('corrierteste1@isep.ipp.pt', 'corrierteste1',2);
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(234344288, 'corrierteste1','corrierteste1@isep.ipp.pt');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(234344288, 3,80,'true');

INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('corrierteste2@isep.ipp.pt', 'corrierteste2',2);
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(234344289, 'corrierteste2','corrierteste2@isep.ipp.pt');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(234344289, 3,70,'true');

INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('corrierteste3@isep.ipp.pt', 'corrierteste3',2);
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(234344290, 'corrierteste3','corrierteste3@isep.ipp.pt');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(234344290, 4,76,'true');

INSERT INTO USER_ENTRY (EMAIL, PASSWORD, FK_USER_ROLE_ID) VALUES('corrierteste4@isep.ipp.pt', 'corrierteste4',2);
INSERT INTO PERSON (NIF, NAME, EMAIL) VALUES(234344291, 'corrierteste4','corrierteste4@isep.ipp.pt');
INSERT INTO COURIER (FK_PERSON_NIF, FK_PHARMACY_ID, WEIGHT, ISWORKING ) VALUES(234344291, 4,65,'true');
**/





